apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tlsdnwn55/argocd-study-example
    targetRevision: HEAD
    path: nginx-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mgmt-nginx
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

