apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-chart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-chart
  template:
    metadata:
      labels:
        app: nginx-chart
    spec:
      containers:
      - name: nginx
        image: nginx:1.26.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: index-html
        configMap:
          name: nginx-chart
